export interface LegacyProductItem {
  title: string;
  description: string;
  price: number;
  category: string;
  images: string[];
  stock: number;
  ratingAvg: number;
  reviewCount: number;
  status: "approved";
}

export const ALL_LEGACY_PRODUCTS: LegacyProductItem[] = [
  // Love Cards
  {
    title: "Heart Card",
    description: "A celebratory handcrafted Heart Card with full of love.",
    price: 20.00,
    category: "Love Cards",
    images: ["/product1.jpg"],
    stock: 25,
    ratingAvg: 4.9,
    reviewCount: 14,
    status: "approved",
  },
  {
    title: "Small Cards",
    description: "An elegant handcrafted small cards with full of love.",
    price: 25.00,
    category: "Love Cards",
    images: ["/product2.jpg"],
    stock: 20,
    ratingAvg: 4.8,
    reviewCount: 9,
    status: "approved",
  },
  {
    title: "Wanna be yours",
    description: "An elegant handcrafted Wanna be yours card with full of love.",
    price: 20.00,
    category: "Love Cards",
    images: ["/product3.jpg"],
    stock: 30,
    ratingAvg: 5.0,
    reviewCount: 22,
    status: "approved",
  },
  {
    title: "Love card",
    description: "An elegant handcrafted love card with full of love.",
    price: 20.00,
    category: "Love Cards",
    images: ["/love card.jpg"],
    stock: 18,
    ratingAvg: 4.9,
    reviewCount: 15,
    status: "approved",
  },
  {
    title: "Love card 2",
    description: "An elegant handcrafted love card 2 with full of love.",
    price: 25.00,
    category: "Love Cards",
    images: ["/love card2.jpg"],
    stock: 15,
    ratingAvg: 4.7,
    reviewCount: 11,
    status: "approved",
  },
  {
    title: "Love card 3",
    description: "An elegant handcrafted love card 3 with full of love.",
    price: 30.00,
    category: "Love Cards",
    images: ["/love card3.jpg"],
    stock: 12,
    ratingAvg: 5.0,
    reviewCount: 19,
    status: "approved",
  },
  {
    title: "Love card 4",
    description: "An elegant handcrafted love card 4 with full of love.",
    price: 20.00,
    category: "Love Cards",
    images: ["/love card4.jpg"],
    stock: 22,
    ratingAvg: 4.8,
    reviewCount: 8,
    status: "approved",
  },

  // Gift Cards
  {
    title: "Cuti Pie",
    description: "A heartfelt handcrafted birthday card with floral designs.",
    price: 20.00,
    category: "Gift Cards",
    images: ["/product5.jpg"],
    stock: 35,
    ratingAvg: 4.9,
    reviewCount: 17,
    status: "approved",
  },
  {
    title: "Red Card",
    description: "A festive handcrafted Mini Cards with holiday decorations.",
    price: 25.00,
    category: "Gift Cards",
    images: ["/product4.jpg"],
    stock: 20,
    ratingAvg: 4.6,
    reviewCount: 10,
    status: "approved",
  },
  {
    title: "Graduation Card",
    description: "A celebratory handcrafted graduation card with a cap and diploma.",
    price: 25.00,
    category: "Gift Cards",
    images: ["/product6.jpg"],
    stock: 18,
    ratingAvg: 4.9,
    reviewCount: 13,
    status: "approved",
  },

  // Mini Cards
  {
    title: "Mini Cards",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 15.00,
    category: "Mini Cards",
    images: ["/product3.jpg"],
    stock: 40,
    ratingAvg: 4.8,
    reviewCount: 25,
    status: "approved",
  },
  {
    title: "Mini Card1",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 10.00,
    category: "Mini Cards",
    images: ["/images/minicard1.jpg"],
    stock: 30,
    ratingAvg: 4.7,
    reviewCount: 12,
    status: "approved",
  },
  {
    title: "Mini Card2",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 15.00,
    category: "Mini Cards",
    images: ["/images/minicard2.jpg"],
    stock: 25,
    ratingAvg: 4.9,
    reviewCount: 18,
    status: "approved",
  },
  {
    title: "Mini Card3",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 10.00,
    category: "Mini Cards",
    images: ["/images/minicard3.jpg"],
    stock: 30,
    ratingAvg: 4.6,
    reviewCount: 9,
    status: "approved",
  },
  {
    title: "Mini Card4",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 15.00,
    category: "Mini Cards",
    images: ["/images/minicard4.jpg"],
    stock: 28,
    ratingAvg: 4.8,
    reviewCount: 14,
    status: "approved",
  },
  {
    title: "Mini Card5",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 20.00,
    category: "Mini Cards",
    images: ["/images/minicard5.jpg"],
    stock: 20,
    ratingAvg: 4.9,
    reviewCount: 16,
    status: "approved",
  },
  {
    title: "Mini Card6",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 10.00,
    category: "Mini Cards",
    images: ["/images/minicard6.jpg"],
    stock: 35,
    ratingAvg: 4.7,
    reviewCount: 11,
    status: "approved",
  },
  {
    title: "Mini Card7",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 20.00,
    category: "Mini Cards",
    images: ["/images/minicard7.jpg"],
    stock: 22,
    ratingAvg: 4.9,
    reviewCount: 13,
    status: "approved",
  },
  {
    title: "Mini Card8",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 15.00,
    category: "Mini Cards",
    images: ["/images/minicard8.jpg"],
    stock: 26,
    ratingAvg: 4.8,
    reviewCount: 15,
    status: "approved",
  },
  {
    title: "Mini Card9",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 20.00,
    category: "Mini Cards",
    images: ["/images/minicard9.jpg"],
    stock: 19,
    ratingAvg: 5.0,
    reviewCount: 20,
    status: "approved",
  },
  {
    title: "Mini Card10",
    description: "An elegant handcrafted Mini Cards with full of love.",
    price: 10.00,
    category: "Mini Cards",
    images: ["/images/minicard10.jpg"],
    stock: 30,
    ratingAvg: 4.7,
    reviewCount: 10,
    status: "approved",
  },

  // Offer Cards
  {
    title: "offercard1",
    description: "A celebratory handcrafted offers.",
    price: 20.00,
    category: "Offer Cards",
    images: ["/offer1.jpg"],
    stock: 40,
    ratingAvg: 4.9,
    reviewCount: 25,
    status: "approved",
  },
  {
    title: "offercard2",
    description: "A celebratory handcrafted offers.",
    price: 20.00,
    category: "Offer Cards",
    images: ["/offer2.jpg"],
    stock: 35,
    ratingAvg: 4.8,
    reviewCount: 19,
    status: "approved",
  },
  {
    title: "offercard3",
    description: "A celebratory handcrafted offers.",
    price: 20.00,
    category: "Offer Cards",
    images: ["/offer3.jpg"],
    stock: 38,
    ratingAvg: 4.9,
    reviewCount: 21,
    status: "approved",
  },

  // Vintage Cards
  {
    title: "Vintagecard1",
    description: "A handcrafted Vintage cards.",
    price: 20.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard1.jpg"],
    stock: 25,
    ratingAvg: 4.8,
    reviewCount: 14,
    status: "approved",
  },
  {
    title: "Vintagecard2",
    description: "A handcrafted Vintage cards.",
    price: 25.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard2.jpg"],
    stock: 20,
    ratingAvg: 4.9,
    reviewCount: 18,
    status: "approved",
  },
  {
    title: "Vintagecard3",
    description: "A handcrafted Vintage cards.",
    price: 20.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard3.jpg"],
    stock: 22,
    ratingAvg: 4.7,
    reviewCount: 12,
    status: "approved",
  },
  {
    title: "Vintagecard4",
    description: "A handcrafted Vintage cards.",
    price: 30.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard4.jpg"],
    stock: 15,
    ratingAvg: 5.0,
    reviewCount: 20,
    status: "approved",
  },
  {
    title: "Vintagecard5",
    description: "A handcrafted Vintage cards.",
    price: 25.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard5.jpg"],
    stock: 18,
    ratingAvg: 4.8,
    reviewCount: 16,
    status: "approved",
  },
  {
    title: "Vintagecard6",
    description: "A handcrafted Vintage cards.",
    price: 20.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard6.jpg"],
    stock: 25,
    ratingAvg: 4.7,
    reviewCount: 11,
    status: "approved",
  },
  {
    title: "Vintagecard7",
    description: "A handcrafted Vintage cards.",
    price: 20.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard7.jpg"],
    stock: 24,
    ratingAvg: 4.9,
    reviewCount: 15,
    status: "approved",
  },
  {
    title: "Vintagecard8",
    description: "A handcrafted Vintage cards.",
    price: 20.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard8.jpg"],
    stock: 22,
    ratingAvg: 4.8,
    reviewCount: 13,
    status: "approved",
  },
  {
    title: "Vintagecard9",
    description: "A handcrafted Vintage cards.",
    price: 25.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard9.jpg"],
    stock: 19,
    ratingAvg: 4.9,
    reviewCount: 17,
    status: "approved",
  },
  {
    title: "Vintagecard10",
    description: "A handcrafted Vintage cards.",
    price: 20.00,
    category: "Vintage Cards",
    images: ["/images/vintagecard10.jpg"],
    stock: 25,
    ratingAvg: 4.7,
    reviewCount: 14,
    status: "approved",
  },

  // Oil Painting Cards
  {
    title: "Oil Painting Card 1",
    description: "A handcrafted Oil Painting Card.",
    price: 20.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting1.jpg"],
    stock: 20,
    ratingAvg: 4.9,
    reviewCount: 15,
    status: "approved",
  },
  {
    title: "Oil Painting Card 2",
    description: "A handcrafted Oil Painting Card.",
    price: 30.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting2.jpg"],
    stock: 15,
    ratingAvg: 5.0,
    reviewCount: 22,
    status: "approved",
  },
  {
    title: "Oil Painting Card 3",
    description: "A handcrafted Oil Painting Card.",
    price: 35.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting3.jpg"],
    stock: 12,
    ratingAvg: 4.9,
    reviewCount: 18,
    status: "approved",
  },
  {
    title: "Oil Painting Card 4",
    description: "A handcrafted Oil Painting Card.",
    price: 20.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting4.jpg"],
    stock: 25,
    ratingAvg: 4.8,
    reviewCount: 14,
    status: "approved",
  },
  {
    title: "Oil Painting Card 5",
    description: "A handcrafted Oil Painting Card.",
    price: 25.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting5.jpg"],
    stock: 20,
    ratingAvg: 4.9,
    reviewCount: 16,
    status: "approved",
  },
  {
    title: "Oil Painting Card 6",
    description: "A handcrafted Oil Painting Card.",
    price: 30.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting6.jpg"],
    stock: 18,
    ratingAvg: 5.0,
    reviewCount: 19,
    status: "approved",
  },
  {
    title: "Oil Painting Card 7",
    description: "A handcrafted Oil Painting Card.",
    price: 25.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting7.jpg"],
    stock: 22,
    ratingAvg: 4.8,
    reviewCount: 15,
    status: "approved",
  },
  {
    title: "Oil Painting Card 8",
    description: "A handcrafted Oil Painting Card.",
    price: 20.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting8.jpg"],
    stock: 25,
    ratingAvg: 4.7,
    reviewCount: 12,
    status: "approved",
  },
  {
    title: "Oil Painting Card 9",
    description: "A handcrafted Oil Painting Card.",
    price: 30.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting9.jpg"],
    stock: 16,
    ratingAvg: 4.9,
    reviewCount: 17,
    status: "approved",
  },
  {
    title: "Oil Painting Card 10",
    description: "A handcrafted Oil Painting Card.",
    price: 20.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting10.jpg"],
    stock: 24,
    ratingAvg: 4.8,
    reviewCount: 14,
    status: "approved",
  },
  {
    title: "Oil Painting Card 11",
    description: "A handcrafted Oil Painting Card.",
    price: 25.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting11.jpg"],
    stock: 20,
    ratingAvg: 4.9,
    reviewCount: 16,
    status: "approved",
  },
  {
    title: "Oil Painting Card 12",
    description: "A handcrafted Oil Painting Card.",
    price: 30.00,
    category: "Oil Painting Cards",
    images: ["/images/oilpainting12.jpg"],
    stock: 18,
    ratingAvg: 5.0,
    reviewCount: 20,
    status: "approved",
  },

  // Book Marks
  {
    title: "Bookmark1",
    description: "A handcrafted Bookmark.",
    price: 10.00,
    category: "Book Marks",
    images: ["/images/bookmark1.jpg"],
    stock: 35,
    ratingAvg: 4.8,
    reviewCount: 18,
    status: "approved",
  },
  {
    title: "Bookmark2",
    description: "A handcrafted Bookmark.",
    price: 15.00,
    category: "Book Marks",
    images: ["/images/bookmark2.jpg"],
    stock: 30,
    ratingAvg: 4.9,
    reviewCount: 20,
    status: "approved",
  },
  {
    title: "Bookmark3",
    description: "A handcrafted Bookmark.",
    price: 5.00,
    category: "Book Marks",
    images: ["/images/bookmark3.jpg"],
    stock: 50,
    ratingAvg: 4.7,
    reviewCount: 15,
    status: "approved",
  },
  {
    title: "Bookmark4",
    description: "A handcrafted Bookmark.",
    price: 10.00,
    category: "Book Marks",
    images: ["/images/bookmark4.jpg"],
    stock: 40,
    ratingAvg: 4.8,
    reviewCount: 17,
    status: "approved",
  },
  {
    title: "Bookmark5",
    description: "A handcrafted Bookmark.",
    price: 15.00,
    category: "Book Marks",
    images: ["/images/bookmark5.jpg"],
    stock: 32,
    ratingAvg: 4.9,
    reviewCount: 22,
    status: "approved",
  },
  {
    title: "Bookmark6",
    description: "A handcrafted Bookmark.",
    price: 5.00,
    category: "Book Marks",
    images: ["/images/bookmark6.jpg"],
    stock: 45,
    ratingAvg: 4.7,
    reviewCount: 14,
    status: "approved",
  },
  {
    title: "Bookmark7",
    description: "A handcrafted Bookmark.",
    price: 10.00,
    category: "Book Marks",
    images: ["/images/bookmark7.jpg"],
    stock: 38,
    ratingAvg: 4.8,
    reviewCount: 19,
    status: "approved",
  },
  {
    title: "Bookmark8",
    description: "A handcrafted Bookmark.",
    price: 10.00,
    category: "Book Marks",
    images: ["/images/bookmark8.jpg"],
    stock: 35,
    ratingAvg: 4.8,
    reviewCount: 16,
    status: "approved",
  },
  {
    title: "Bookmark9",
    description: "A handcrafted Bookmark.",
    price: 15.00,
    category: "Book Marks",
    images: ["/images/bookmark9.jpg"],
    stock: 28,
    ratingAvg: 4.9,
    reviewCount: 21,
    status: "approved",
  },
  {
    title: "Bookmark10",
    description: "A handcrafted Bookmark.",
    price: 10.00,
    category: "Book Marks",
    images: ["/images/bookmark10.jpg"],
    stock: 35,
    ratingAvg: 4.8,
    reviewCount: 17,
    status: "approved",
  },
  {
    title: "Bookmark11",
    description: "A handcrafted Bookmark.",
    price: 10.00,
    category: "Book Marks",
    images: ["/images/bookmark11.jpg"],
    stock: 36,
    ratingAvg: 4.8,
    reviewCount: 15,
    status: "approved",
  },
  {
    title: "Bookmark12",
    description: "A handcrafted Bookmark.",
    price: 5.00,
    category: "Book Marks",
    images: ["/images/bookmark12.jpg"],
    stock: 48,
    ratingAvg: 4.7,
    reviewCount: 13,
    status: "approved",
  },
  {
    title: "Bookmark13",
    description: "A handcrafted Bookmark.",
    price: 10.00,
    category: "Book Marks",
    images: ["/images/bookmark13.jpg"],
    stock: 34,
    ratingAvg: 4.8,
    reviewCount: 16,
    status: "approved",
  },
  {
    title: "Bookmark14",
    description: "A handcrafted Bookmark.",
    price: 10.00,
    category: "Book Marks",
    images: ["/images/bookmark14.jpg"],
    stock: 35,
    ratingAvg: 4.8,
    reviewCount: 18,
    status: "approved",
  },
  {
    title: "Bookmark15",
    description: "A handcrafted Bookmark.",
    price: 5.00,
    category: "Book Marks",
    images: ["/images/bookmark15.jpg"],
    stock: 50,
    ratingAvg: 4.7,
    reviewCount: 14,
    status: "approved",
  },

  // Mini Frames
  {
    title: "Miniframe1",
    description: "A handcrafted Miniframe.",
    price: 10.00,
    category: "Mini Frames",
    images: ["/images/miniframes1.jpg"],
    stock: 30,
    ratingAvg: 4.8,
    reviewCount: 16,
    status: "approved",
  },
  {
    title: "Miniframe2",
    description: "A handcrafted Miniframe.",
    price: 25.00,
    category: "Mini Frames",
    images: ["/images/miniframes2.jpg"],
    stock: 22,
    ratingAvg: 4.9,
    reviewCount: 19,
    status: "approved",
  },
  {
    title: "Miniframe3",
    description: "A handcrafted Miniframe.",
    price: 30.00,
    category: "Mini Frames",
    images: ["/images/miniframes3.jpg"],
    stock: 18,
    ratingAvg: 5.0,
    reviewCount: 23,
    status: "approved",
  },
  {
    title: "Miniframe4",
    description: "A handcrafted Miniframe.",
    price: 20.00,
    category: "Mini Frames",
    images: ["/images/miniframes4.jpg"],
    stock: 25,
    ratingAvg: 4.8,
    reviewCount: 15,
    status: "approved",
  },
  {
    title: "Miniframe5",
    description: "A handcrafted Miniframe.",
    price: 25.00,
    category: "Mini Frames",
    images: ["/images/miniframes5.jpg"],
    stock: 20,
    ratingAvg: 4.9,
    reviewCount: 18,
    status: "approved",
  },
  {
    title: "Miniframe6",
    description: "A handcrafted Miniframe.",
    price: 15.00,
    category: "Mini Frames",
    images: ["/images/miniframes6.jpg"],
    stock: 28,
    ratingAvg: 4.7,
    reviewCount: 14,
    status: "approved",
  },
  {
    title: "Miniframe7",
    description: "A handcrafted Miniframe.",
    price: 20.00,
    category: "Mini Frames",
    images: ["/images/miniframes7.jpg"],
    stock: 25,
    ratingAvg: 4.8,
    reviewCount: 16,
    status: "approved",
  },
  {
    title: "Miniframe8",
    description: "A handcrafted Miniframe.",
    price: 25.00,
    category: "Mini Frames",
    images: ["/images/miniframes8.jpg"],
    stock: 21,
    ratingAvg: 4.9,
    reviewCount: 17,
    status: "approved",
  },
  {
    title: "Miniframe9",
    description: "A handcrafted Miniframe.",
    price: 20.00,
    category: "Mini Frames",
    images: ["/images/miniframes9.jpg"],
    stock: 24,
    ratingAvg: 4.8,
    reviewCount: 15,
    status: "approved",
  },
];
